### PR TITLE
Update showTotalLightningBalance.sh

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gcomte** [comment]
Wow, this is helpful thank you!

For me the CONTROL_SUM does not add up to the initially deposited amount, because the following variables are missing:
- ONCHAIN_IN_AND_OUT
- ONCHAIN_COMMIT_FEES

**Comment by ghost** [comment]
Thanks for a hints. However for me (no on-chain out), no closed channel and on chain fees ~30k sats max, and the difference is 100k+ sats.

I will look at it at evening :)

**Comment by ghost** [comment]
Further notes:

- It is hard to calculate with ON-CHAIN transactions (it is needed to distinquish OUT TXs from OPEN_CHANNEL TXs) probably only possible by matching TX hashes -> **script calculates with total-balance** as it is more "easy"

Issues to work on:
- [ ] Funds locked in "opening channels" (command `lncli pendingchannels`) are not counted (yet?) the problem is that some channels may be "lost" (for example they will never open - by invalid openning transaction) I need to find a way how to distinquish between them. Also channels can be abandoned, but it works only on debug complied lnd.
- [ ] in my channel there is error of `2 sats` and I have no idea why (i need to check rounding in channel balances)

**Comment by ghost** [comment]
I am satisfied with a script as is, feel free to further update it if you feel it needs it.

- I havent used much of BTC values (i just use sats).

Maybe also splitting script to two may be useful (one is original one with "balance" and second with "accounting").

**Comment by gcomte** [comment]
Excellent work, děkuju!!

**Pull request merged**
